CREATE TABLE `matches` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT 'Match''s ID',
  `league` int DEFAULT NULL COMMENT 'League''s ID',
  `season` int DEFAULT NULL COMMENT 'Season''s ID',
  `home_team` int DEFAULT NULL COMMENT 'Id of a home team',
  `away_team` int DEFAULT NULL COMMENT 'Id of an away team',
  `game_date` datetime DEFAULT NULL COMMENT 'Date of a game',
  `home_team_goals` int DEFAULT NULL COMMENT 'Number of goals scored by home team',
  `away_team_goals` int DEFAULT NULL COMMENT 'Number of goals scored by away team',
  `home_team_xg` float DEFAULT NULL COMMENT 'XG - Expected goals',
  `away_team_xg` float DEFAULT NULL COMMENT 'XG - Expected goals',
  `home_team_bp` int DEFAULT NULL COMMENT 'BP - Ball Possesion',
  `away_team_bp` int DEFAULT NULL COMMENT 'BP - Ball Possesion',
  `home_team_sc` int DEFAULT NULL COMMENT 'SC - Scoring Chances',
  `away_team_sc` int DEFAULT NULL COMMENT 'SC - Scoring Chances',
  `home_team_sog` int DEFAULT NULL COMMENT 'SOG - Shots on Goal',
  `away_team_sog` int DEFAULT NULL,
  `home_team_fk` int DEFAULT NULL COMMENT 'FK - Free Kicks',
  `away_team_fk` int DEFAULT NULL COMMENT 'FK - Free Kicks',
  `home_team_ck` int DEFAULT NULL COMMENT 'CK - Corner Kicks',
  `away_team_ck` int DEFAULT NULL COMMENT 'CK - Corner Kicks',
  `home_team_off` int DEFAULT NULL COMMENT 'off - Offsides',
  `away_team_off` int DEFAULT NULL COMMENT 'off - Offsides',
  `home_team_fouls` int DEFAULT NULL,
  `away_team_fouls` int DEFAULT NULL,
  `home_team_yc` int DEFAULT NULL,
  `away_team_yc` int DEFAULT NULL COMMENT 'YC - Yellow Cards',
  `home_team_rc` int DEFAULT NULL COMMENT 'RC - Red Cards',
  `away_team_rc` int DEFAULT NULL,
  `result` varchar(1) COLLATE utf8mb3_polish_ci DEFAULT NULL COMMENT 'Result of a match. 1 - Home team won, X - draw, 2 - Away team won',
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  KEY `SeasonFK_idx` (`season`),
  KEY `LeagueFK2_idx` (`league`),
  KEY `TeamsFK_idx` (`home_team`),
  KEY `TeamsFK2_idx` (`away_team`),
  CONSTRAINT `LeagueFK2` FOREIGN KEY (`league`) REFERENCES `leagues` (`id`),
  CONSTRAINT `SeasonFK` FOREIGN KEY (`season`) REFERENCES `seasons` (`id`),
  CONSTRAINT `TeamsFK` FOREIGN KEY (`home_team`) REFERENCES `teams` (`id`),
  CONSTRAINT `TeamsFK2` FOREIGN KEY (`away_team`) REFERENCES `teams` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8218 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_polish_ci COMMENT='Table containg all matches considered in analysis'