/*
-- Query: select * from teams
LIMIT 0, 10000

-- Date: 2024-03-10 18:50
*/
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (1,1,'Śląsk Wrocław');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (2,1,'Jagiellonia Białystok');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (3,1,'Lech Poznań');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (4,1,'Raków Częstochowa');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (5,1,'Legia Warszawa');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (6,1,'Pogoń Szczecin');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (7,1,'Górnik Zabrze');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (8,1,'Zagłębie Lubin');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (9,1,'Piast Gliwice');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (10,1,'Radomiak Radom');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (11,1,'Stal Mielec');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (12,1,'Widzew Łódź');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (13,1,'Cracovia');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (14,1,'Puszcza Niepołomice');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (15,1,'Warta Poznań');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (16,1,'Korona Kielce');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (17,1,'Ruch Chorzów');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (18,1,'ŁKS Łódź');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (19,1,'Wisła Płock');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (20,1,'Lechia Gdańsk');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (21,1,'Miedź Legnica');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (22,1,'Bruk-Bet Termalica Nieciecza');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (23,1,'Wisła Kraków');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (24,1,'Górnik Łęczna');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (26,1,'Podbeskidzie Bielsko-Biała');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (27,1,'Arka Gdynia');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (28,1,'Zagłębie Sosnowiec');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (29,1,'Sandecja Nowy Sącz');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (30,1,'Stal Rzeszów');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (31,1,'Chrobry Głogów');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (32,1,'GKS Katowice');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (33,1,'GKS Tychy');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (34,1,'Resovia Rzeszów');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (35,1,'Odra Opole');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (36,1,'Skra Częstochowa');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (37,1,'Chojniczanka');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (38,1,'Stomil Olsztyn');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (39,1,'Górnik Polkowice');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (40,1,'GKS Jastrzębie');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (41,1,'GKS Bełchatów');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (42,1,'Olimpia Grudziądz');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (43,1,'Wigry Suwałki');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (44,1,'Bytovia Bytów');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (45,1,'Garbarnia Kraków');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (46,1,'Pogoń Siedlce');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (47,1,'Wisła Puławy');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (48,1,'Znicz Pruszków');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (49,1,'MKS Kluczbork');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (51,2,'Liverpool');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (52,2,'Manchester City');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (53,2,'Arsenal');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (54,2,'Aston Villa');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (55,2,'Tottenham');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (56,2,'Manchester Utd');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (57,2,'West Ham');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (58,2,'Newcastle');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (59,2,'Brighton');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (60,2,'Wolves');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (61,2,'Chelsea');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (62,2,'Fulham');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (63,2,'Bournemouth');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (64,2,'Crystal Palace');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (65,2,'Brentford');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (66,2,'Everton');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (67,2,'Nottingham');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (68,2,'Luton');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (69,2,'Burnley');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (70,2,'Sheffield Utd');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (71,2,'Leicester');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (72,2,'Leeds');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (73,2,'Southampton');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (74,2,'Burnley');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (75,2,'Watford');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (76,2,'Norwich');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (77,2,'West Brom');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (78,2,'Cardiff');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (79,2,'Huddersfield');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (80,2,'Swansea');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (81,2,'Stoke');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (82,2,'Hull');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (83,2,'Sunderland');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (84,2,'Middlesbrough');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (85,2,'Coventry');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (86,2,'Blackburn');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (87,2,'Millwall');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (88,2,'Preston');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (89,2,'Bristol City');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (90,2,'Birmingham');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (91,2,'Rotherham');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (92,2,'QPR');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (93,2,'Reading');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (94,2,'Blackpool');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (95,2,'Wigan');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (96,2,'Peterborough');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (97,2,'Peterborough');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (98,2,'Barnsley');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (99,2,'Wycombe');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (100,2,'Sheffield Wed');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (101,2,'Charlton');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (102,2,'Ipswich');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (103,2,'Bolton');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (104,2,'Burton');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (105,3,'PSG');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (106,3,'Lens');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (107,3,'Marsylia');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (108,3,'Rennes');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (109,3,'Lille');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (110,3,'Monaco');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (111,3,'Lyon');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (112,3,'Clermont');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (113,3,'Nice');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (114,3,'Lorient');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (115,3,'Reims');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (116,3,'Montpellier');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (117,3,'Toulouse');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (118,3,'Brest');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (119,3,'Strasbourg');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (120,3,'Nantes');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (121,3,'Auxerre');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (122,3,'AC Ajaccio');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (123,3,'Troyes');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (124,3,'Angers');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (125,3,'St. Etienne');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (126,3,'Metz');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (127,3,'Bordeaux');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (128,3,'Sochaux');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (129,3,'Paris FC');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (130,3,'Nimes');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (131,3,'Dijon');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (132,3,'Grenoble');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (133,3,'Amiens');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (134,3,'Caen');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (135,3,'Guingamp');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (136,3,'Le Havre');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (137,3,'Nancy');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (138,3,'Bastia');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (139,3,'Quevilly Rouen');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (140,3,'Pau FC');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (141,3,'Rodez');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (142,3,'Laval');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (143,3,'Valenciennes');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (144,3,'Annecy');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (145,3,'Niort');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (146,3,'Villefranche');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (147,3,'Dunkerque');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (148,3,'Chambly');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (149,3,'Le Mans');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (150,3,'Orleans');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (151,3,'GFC Ajaccio');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (152,3,'Beziers');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (153,3,'Red Star');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (154,4,'Bayern Monachium');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (155,4,'Borussia Dortmund');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (156,4,'RB Lipsk');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (157,4,'1. FC Union Berlin');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (158,4,'SC Freiburg');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (159,4,'Bayer Leverkusen');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (160,4,'Eintracht Frankfurt');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (161,4,'VfL Wolfsburg');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (162,4,'1. FSV Mainz 05');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (163,4,'B. Moenchengladbach');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (164,4,'1. FC Koeln');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (165,4,'TSG Hoffenheim');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (166,4,'Werder Brema');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (167,4,'Bochum');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (168,4,'FC Augsburg');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (169,4,'VfB Stuttgart');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (170,4,'FC Schalke 04');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (171,4,'Hertha Berlin');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (172,4,'Arminia Bielefeld');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (173,4,'Furth');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (174,4,'Düsseldorf');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (175,4,'Paderborn');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (176,4,'Hannover');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (177,4,'1. FC Nürnberg');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (178,4,'Hamburger SV');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (179,4,'Ingolstadt');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (180,4,'Darmstadt');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (181,4,'Braunschweig');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (182,4,'Kiel');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (183,4,'Heidenheim');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (184,4,'Wehen');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (185,4,'St. Pauli');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (186,4,'Karlsruher');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (187,4,'Kaiserslautern');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (188,4,'Magdeburg');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (189,4,'Rostock');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (190,4,'Regensburg');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (191,4,'Sandhausen');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (192,4,'Dresden');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (193,4,'Aue');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (194,4,'Osnabruck');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (195,4,'Wurzburger Kickers');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (196,4,'Duisburg');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (197,4,'Monachium 1860');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (198,5,'Napoli');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (199,5,'Lazio');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (200,5,'Inter');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (201,5,'AC Milan');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (202,5,'Atalanta');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (203,5,'AS Roma');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (204,5,'Juventus');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (205,5,'Fiorentina');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (206,5,'Bologna');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (207,5,'Torino');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (208,5,'Monza');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (209,5,'Udinese');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (210,5,'Sassuolo');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (211,5,'Empoli');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (212,5,'Salernitana');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (213,5,'Lecce');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (214,5,'Spezia');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (215,5,'Verona');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (216,5,'Cremonese');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (217,5,'Sampdoria');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (218,5,'Cagliari');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (219,5,'Genoa');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (220,5,'Venezia');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (221,5,'Benevento');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (222,5,'Crotone');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (223,5,'Parma');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (224,5,'Brescia');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (225,5,'Spal');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (226,5,'Frosinone');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (227,5,'Chievo');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (228,5,'Palermo');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (229,5,'Pescara');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (230,5,'Bari');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (231,5,'Sudtirol');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (232,5,'Reggio Calabria');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (233,5,'Modena');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (234,5,'Pisa');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (235,5,'Ascoli');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (236,5,'Como');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (237,5,'Ternana');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (238,5,'Cittadella');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (239,5,'Cosenza');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (240,5,'Perugia');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (241,5,'L.R. Vicenza');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (242,5,'Alessandria');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (243,5,'Pordenone');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (244,5,'Reggiana');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (245,5,'Entella');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (246,5,'Trapani');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (247,5,'Juve Stabia');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (248,5,'Livorno');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (249,5,'Foggia');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (250,5,'Padova');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (251,5,'AC Carpi');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (252,5,'Cesena');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (253,5,'Avellino');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (254,5,'Novara');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (255,5,'Pro Vercelli');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (256,5,'Latina');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (257,7,'Barcelona');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (258,7,'Real Madryt');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (259,7,'Atl. Madryt');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (260,7,'Real Sociedad');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (261,7,'Villarreal');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (262,7,'Betis');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (263,7,'Osasuna');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (264,7,'Ath. Bilbao');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (265,7,'Mallorca');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (266,7,'Girona');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (267,7,'Vallecano');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (268,7,'Sevilla');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (269,7,'Celta Vigo');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (270,7,'Cadiz');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (271,7,'Getafe');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (272,7,'Valencia');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (273,7,'Almeria');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (274,7,'Valladolid');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (275,7,'Espanyol');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (276,7,'Elche');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (277,7,'Granada');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (278,7,'Levante');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (279,7,'Alaves');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (280,7,'Huesca');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (281,7,'Eibar');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (282,7,'Leganes');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (283,7,'La Coruna');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (284,7,'Las Palmas');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (285,7,'Malaga');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (286,7,'Gijon');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (287,7,'Albacete');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (288,7,'Andorra');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (289,7,'R. Oviedo');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (290,7,'Cartagena');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (291,7,'Tenerife');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (292,7,'Burgos CF');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (293,7,'Racing Santander');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (294,7,'Zaragoza');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (295,7,'Mirandes');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (296,7,'Villarreal B');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (297,7,'Ponferradina');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (298,7,'UD Ibiza');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (299,7,'Lugo');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (300,7,'Amorebieta');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (301,7,'R. Sociedad B');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (302,7,'Fuenlabrada');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (303,7,'Alcorcon');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (304,7,'Sabadell');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (305,7,'UD Logrones');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (306,7,'Castellon');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (307,7,'Numancia');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (308,7,'Extremadura UD');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (309,7,'Rayo Majadahonda');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (310,7,'Gimnastic');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (311,7,'Cordoba');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (312,7,'Reus FCR');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (313,7,'Cultural Leonesa');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (314,7,'Barcelona B');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (315,7,'Lorca FC');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (316,7,'Sevilla B');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (317,7,'UCAM Murcia');
