/*
-- Query: select * from teams
LIMIT 0, 10000

-- Date: 2024-03-09 00:06
*/
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (1,1,'Śląsk Wrocław');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (2,1,'Jagiellonia Białystok');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (3,1,'Lech Poznań');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (4,1,'Raków Częstochowa');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (5,1,'Legia Warszawa');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (6,1,'Pogoń Szczecin');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (7,1,'Górnik Zabrze');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (8,1,'Zagłębie Lubin');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (9,1,'Piast Gliwice');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (10,1,'Radomiak Radom');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (11,1,'Stal Mielec');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (12,1,'Widzew Łódź');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (13,1,'Cracovia');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (14,1,'Puszcza Niepołomice');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (15,1,'Warta Poznań');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (16,1,'Korona Kielce');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (17,1,'Ruch Chorzów');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (18,1,'ŁKS Łódź');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (19,1,'Wisła Płock');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (20,1,'Lechia Gdańsk');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (21,1,'Miedź Legnica');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (22,1,'Bruk-Bet Termalica Nieciecza');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (23,1,'Wisła Kraków');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (24,1,'Górnik Łęczna');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (26,1,'Podbeskidzie Bielsko-Biała');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (27,1,'Arka Gdynia');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (28,1,'Zagłębie Sosnowiec');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (29,1,'Sandecja Nowy Sącz');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (30,1,'Stal Rzeszów');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (31,1,'Chrobry Głogów');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (32,1,'GKS Katowice');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (33,1,'GKS Tychy');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (34,1,'Resovia Rzeszów');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (35,1,'Odra Opole');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (36,1,'Skra Częstochowa');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (37,1,'Chojniczanka');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (38,1,'Stomil Olsztyn');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (39,1,'Górnik Polkowice');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (40,1,'GKS Jastrzębie');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (41,1,'GKS Bełchatów');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (42,1,'Olimpia Grudziądz');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (43,1,'Wigry Suwałki');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (44,1,'Bytovia Bytów');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (45,1,'Garbarnia Kraków');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (46,1,'Pogoń Siedlce');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (47,1,'Wisła Puławy');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (48,1,'Znicz Pruszków');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (49,1,'MKS Kluczbork');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (51,2,'Liverpool');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (52,2,'Manchester City');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (53,2,'Arsenal');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (54,2,'Aston Villa');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (55,2,'Tottenham');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (56,2,'Manchester Utd');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (57,2,'West Ham');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (58,2,'Newcastle');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (59,2,'Brighton');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (60,2,'Wolves');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (61,2,'Chelsea');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (62,2,'Fulham');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (63,2,'Bournemouth');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (64,2,'Crystal Palace');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (65,2,'Brentford');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (66,2,'Everton');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (67,2,'Nottingham');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (68,2,'Luton');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (69,2,'Burnley');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (70,2,'Sheffield Utd');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (71,2,'Leicester');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (72,2,'Leeds');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (73,2,'Southampton');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (74,2,'Burnley');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (75,2,'Watford');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (76,2,'Norwich');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (77,2,'West Brom');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (78,2,'Cardiff');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (79,2,'Huddersfield');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (80,2,'Swansea');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (81,2,'Stoke');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (82,2,'Hull');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (83,2,'Sunderland');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (84,2,'Middlesbrough');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (85,2,'Coventry');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (86,2,'Blackburn');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (87,2,'Millwall');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (88,2,'Preston');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (89,2,'Bristol City');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (90,2,'Birmingham');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (91,2,'Rotherham');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (92,2,'QPR');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (93,2,'Reading');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (94,2,'Blackpool');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (95,2,'Wigan');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (96,2,'Peterborough');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (97,2,'Peterborough');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (98,2,'Barnsley');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (99,2,'Wycombe');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (100,2,'Sheffield Wed');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (101,2,'Charlton');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (102,2,'Ipswich');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (103,2,'Bolton');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (104,2,'Burton');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (105,3,'PSG');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (106,3,'Lens');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (107,3,'Marsylia');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (108,3,'Rennes');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (109,3,'Lille');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (110,3,'Monaco');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (111,3,'Lyon');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (112,3,'Clermont');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (113,3,'Nice');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (114,3,'Lorient');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (115,3,'Reims');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (116,3,'Montpellier');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (117,3,'Toulouse');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (118,3,'Brest');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (119,3,'Strasbourg');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (120,3,'Nantes');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (121,3,'Auxerre');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (122,3,'AC Ajaccio');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (123,3,'Troyes');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (124,3,'Angers');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (125,3,'St. Etienne');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (126,3,'Metz');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (127,3,'Bordeaux');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (128,3,'Sochaux');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (129,3,'Paris FC');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (130,3,'Nimes');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (131,3,'Dijon');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (132,3,'Grenoble');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (133,3,'Amiens');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (134,3,'Caen');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (135,3,'Guingamp');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (136,3,'Le Havre');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (137,3,'Nancy');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (138,3,'Bastia');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (139,3,'Quevilly Rouen');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (140,3,'Pau FC');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (141,3,'Rodez');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (142,3,'Laval');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (143,3,'Valenciennes');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (144,3,'Annecy');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (145,3,'Niort');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (146,3,'Villefranche');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (147,3,'Dunkerque');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (148,3,'Chambly');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (149,3,'Le Mans');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (150,3,'Orleans');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (151,3,'GFC Ajaccio');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (152,3,'Beziers');
INSERT INTO `teams` (`id`,`country`,`name`) VALUES (153,3,'Red Star');
